services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  api1:
    image: jotahenrique/fraud-detection:v1.5.4
    environment:
      - PORT=8080
      - GOMAXPROCS=1
      - GOGC=off
      - GOMEMLIMIT=150MiB
    networks:
      - rinha
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

  api2:
    image: jotahenrique/fraud-detection:v1.5.4
    environment:
      - PORT=8080
      - GOMAXPROCS=1
      - GOGC=off
      - GOMEMLIMIT=150MiB
    networks:
      - rinha
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

networks:
  rinha:
    driver: bridge
