services:
  nginx:
    image: nginx:alpine
    cpuset: "0,2"
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  api1:
    image: jotahenrique/fraud-detection:v1.5.8
    cpuset: "0-1"
    environment:
      - SOCKET_PATH=/sockets/api1.sock
      - GOMAXPROCS=1
      - GOGC=off
      - GOMEMLIMIT=150MiB
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api1.sock"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

  api2:
    image: jotahenrique/fraud-detection:v1.5.8
    cpuset: "2-3"
    environment:
      - SOCKET_PATH=/sockets/api2.sock
      - GOMAXPROCS=1
      - GOGC=off
      - GOMEMLIMIT=150MiB
    volumes:
      - sockets:/sockets
    networks:
      - rinha
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api2.sock"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m"

networks:
  rinha:
    driver: bridge
