worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    upstream api {
        server unix:/sockets/api1.sock;
        server unix:/sockets/api2.sock;
    }

    server {
        listen 9999;
        proxy_pass api;
    }
}
